### ISSUE TITLE
Add blog posts for Azure Database for MySQL Blog

### ISSUE THREAD

**Issue by HJToland3** [oursqlcommunity-org/planet#106]
Name of blog - Azure Database for MySQL Blog
Link to blog - https://techcommunity.microsoft.com/t5/azure-database-for-mysql-blog/bg-p/ADforMySQL
Link to the corresponding RSS feed - https://techcommunity.microsoft.com/gxcuf89792/rss/board?board.id=ADforMySQL 
Twitter handle (or another way for publicly contacting you) - @AzureDBMySQL
Email address - mysqlsocial@microsoft.com

Please reach out with any questions!  Thanks in advance!

**Comment by jfg956** [comment]
Thanks for submitting an issuse, I will look into this soon.

**Comment by HJToland3** [comment]
[heart]         Jim Toland reacted to your message:
________________________________

**Comment by jfg956** [comment]
Done.  Thanks for you interest in Planet for the MySQL Community.

**Comment by jfg956** [comment]
https://twitter.com/jfg956/status/1724619084564730272

**Comment by jfg956** [comment]
Related: https://github.com/oursqlcommunity-org/planet/commit/7b9e3bc2401f752db0cfc5b5a1c5c6c4dc77fede

**Comment by HJToland3** [comment]
[heart]         Jim Toland reacted to your message:
________________________________

**Comment by HJToland3** [comment]
[heart]         Jim Toland reacted to your message:
________________________________

**Comment by jfg956** [comment]
Hi James, not fully related to this, but can I bring below to your attention.  Thanks, J-F
https://github.com/oursqlcommunity-org/planet/issues/124
