### ISSUE TITLE
A post from MinervaDB Blog was not aggregater.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#114]
Post: https://minervadb.xyz/tips-and-tricks-for-reducing-leaf-block-contention-happening-to-innodb/

Reason: only mentions MySQL once, [and we need it twice](https://github.com/oursqlcommunity-org/planet/issues/105).

Possible fix: add InnoDB to filtering allow-list.

**Comment by jfg956** [comment]
Fixed in below, closing.
https://github.com/oursqlcommunity-org/planet/commit/4ff3ca8b47223e3bcee5c4efe6a645fbe0070df1

**Comment by lefred** [comment]
Please pay attention to that blog. Everything is not relevant. Take a look at: https://minervadb.xyz/understanding-system-versioned-and-application-versioned-temporal-tables-in-mysql-exploring-the-power-of-historical-data-tracking/ (pointed to me by @federico-razzoli)

**Comment by federico-razzoli** [comment]
To be clear the problem with that post in particular is that it's about a feature that doesn't exist. @lefred confirmed this.

**Comment by jfg956** [comment]
Thanks LeFred and Federico.  But unclear what you want me to do as a follow-up action.

Are you suggesting I do not aggregate this blog because it sometime contains information that is not 100% exact ?  Because I am not sure it is the role of an aggregator to do this sort of content validation.  If would probably be better to engage directly with the content producer to have this fixed in the post.

If you want to keep engaging on the subject, please create a new issue as this specific issue was not created for content moderation but for aggregation / filtering  purposes.  Thanks, J-F
