### ISSUE TITLE
MinervaDB posts relaying false information.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#144]
In the past, some people told me the MinervaDB Blog relayed false information.  I did not pay much attention at the time and asked these people to open an issue because I think this needed a wider discussion, but such issue was not created at the time.

Today, my attention was brought back to this.  I commented on LinkedIn about such post, link below.
- https://www.linkedin.com/feed/update/urn:li:activity:7275925173344653313?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7275925173344653313%2C7275935611125989376%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287275935611125989376%2Curn%3Ali%3Aactivity%3A7275925173344653313%29

I am not ready to remove this blog from the aggregator at this time, I do not take this decision lightly, but I think this should be traced in case others have similar complaints in the future.

**Comment by jfg956** [comment]
Screenshots:

<img width="635" alt="Screenshot 2024-12-20 at 13 10 59" src="https://github.com/user-attachments/assets/642d4614-4e3e-4eba-80a9-67afe14216da" />

<img width="1363" alt="Screenshot 2024-12-20 at 13 06 58" src="https://github.com/user-attachments/assets/cdc06adb-181d-4da2-a98a-d7c1cf04e4e9" />

**Comment by shiviyer** [comment]
@jfg956  If there are any technical errors in the posts published by more or any other consultants in our teams we are always happy to correct. Regarding this post, both InnoDB doublewrite and Group Commit are closely related. Let me explain. Both interact with the write-ahead logging (WAL) principle of MySQL, where data changes are first written to logs (redo logs and binary logs) before they are applied to disk. Thus, innodb_doublewrite ensures that page writes are crash-safe by writing to the doublewrite buffer before flushing the data to the actual tablespace, and Group Commit ensures durability of the redo log and binary log writes by grouping multiple transactions and flushing them together in a single fsync() call. Always open to inputs and corrections. You can write to me - shiv@minervadb.com . Thank you!

**Comment by jfg956** [comment]
> You can write to me - shiv@minervadb.com .

Message sent.

**Comment by jfg956** [comment]
Email answered Fri, Dec 20, 3:14 PM.

The post has been taken down, closing this issue.
