### ISSUE TITLE
Add dbadojo.com.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#21]
The post (1) reached Planet MySQL but not Planet for the MySQL Community.  Add the corresponding feed.  Maybe do at the same time as (2).

(1): https://dbadojo.com/2020/06/11/find-a-corrupted-innodb-table-or-a-corrupted-index-from-index-id/

(2): https://github.com/oursqlcommunity-org/planet/issues/20

**Comment by sjmudd** [comment]
Should be completed now.
