### ISSUE TITLE
Add mysqlmed.wordpress.com feed.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#22]
The (1) post reached Planet MySQL but did not reach Planet for the MySQL Community.

(1): https://mysqlmed.wordpress.com/2020/06/11/mysql-innodb-cluster-disaster-recovery-contingency-via-a-group-replication-slave/

**Comment by igroene** [comment]
This was done https://github.com/oursqlcommunity-org/planet/commit/b4f3e40bee92135e67d345dd2b70255d5da98f54
