### ISSUE TITLE
Add feed for oysteing.blogspot.com

### ISSUE THREAD

**Issue by ogrovlen** [oursqlcommunity-org/planet#26]
Name:  Øystein on MySQL Optimizer
Link: https://oysteing.blogspot.com/
Atom 1.0: https://oysteing.blogspot.com/feeds/posts/default
RSS 2.0: https://oysteing.blogspot.com/feeds/posts/default?alt=rss
Twitter: @ogrovlen
Email: oystein.grovlen@gmail.com

**Comment by jfg956** [comment]
To do at the same time as https://github.com/oursqlcommunity-org/planet/issues/25.
