### ISSUE TITLE
Adding mysqlonarm blog to the aggregator

### ISSUE THREAD

**Issue by mysqlonarm** [oursqlcommunity-org/planet#4]
Name of the blog: MySQL On ARM
Blog: https://mysqlonarm.github.io/
RSS feed: https://mysqlonarm.github.io/feed.xml
Twitter handle: #mysqlonarm
Driver: Krunal Bauskar

----
Do let me know if you need more info. Thanks for putting this together.

**Comment by jfg956** [comment]
Hi, thanks for submitting your feed.  I will take care of this soon.

Could you also submit an email address for private communication ?  The logic behind this is described in (1) (contacting authors via Twitter and email) and in (2) (Author Availability Policy).  You can submit it encrypted in this issue (howto in (3)), or by sending a mail at planet AT oursqlcommunity DOT org.

(1): https://jfg-mysql.blogspot.com/2020/05/planet-mysql-community-requirements-rfc.html

(2): https://github.com/oursqlcommunity-org/planet/blob/master/aggregation_and_content_policy.md

(3): https://github.com/oursqlcommunity-org/planet/blob/master/email_encryption_howto.md

Thanks.

**Comment by mysqlonarm** [comment]
Email-id: krunalbauskar@gmail.com

**Comment by igroene** [comment]
added in https://github.com/oursqlcommunity-org/planet/commit/cf9c4a6cdc4da8c5bc4b996b7f8445b86fdc113c
