### ISSUE TITLE
Add koehntopp blog in a smart way.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#48]
The post (1) reached Planet MySQL and not Planet for the MySQL Community. But we probably do not want all posts as some are off-topic, so a solution like for (2) will be needed (or a tagged feed).

(1): https://blog.koehntopp.info/2020/09/03/mysql-json-data-type.html

(2): #7

**Comment by isotopp** [comment]
I made changes, https://blog.koehntopp.info/2020/09/09/feeds-tagged-and-a-mysql-feed.html

There is a feed, https://blog.koehntopp.info/feed_mysql.xml

There are also Tags inside each item in the feed, if you want even more differentiation.

**Comment by isotopp** [comment]
Name: MySQL Posts on Die Wunderbare Welt von Isotopp
Link: https://blog.koehntopp.info
Subfeed: https://blog.koehntopp.info/feed_mysql.xml
Full Feed: https://blog.koehntopp.info/feed.xml
Twitter: @isotopp (lots of non-mysql stuff in there) (german and english)
Email: kristian.koehntopp@gmail.com

**Comment by isotopp** [comment]
I added myself in a dumb way, because that was the smartest solution. Sorry about that. :-)

**Comment by jfg956** [comment]
Thanks for providing a feed Kris.  The "smart" way I have in mind is to filter post containing a few "allow words" like "MySQL" or "MariaDB", but I have yet to implement this filtering and enforce this filtering on only some of the feeds.  Cheers, JFG
