### ISSUE TITLE
Add SqlForDevs.io blog

### ISSUE THREAD

**Issue by tpetry** [oursqlcommunity-org/planet#62]
* The name for your blog: SQL for Devs
* A link to your blog: https://sqlfordevs.io
* A link to the corresponding Atom or RSS feed: https://sqlfordevs.io/feed/mysql
* Your Twitter handle (or another way for publicly contacting you): [@tobias_petry](https://twitter.com/tobias_petry)
* Your email address (encrypted format recommended; or another way for privately contacting you): -

**Comment by jfg956** [comment]
Thanks for the issue Tobias, I will look into that in the next hours.

**Comment by jfg956** [comment]
Done.  Thanks for your submission.
