### ISSUE TITLE
Please add my blog https://of-code.blogspot.com/search/label/mysql

### ISSUE THREAD

**Issue by laurynas-biveinis** [oursqlcommunity-org/planet#63]
- the name for your blog: "Laurynas Biveinis"
- a link to your blog: https://of-code.blogspot.com/search/label/mysql
- a link to the corresponding Atom or RSS feed: http://feeds.feedburner.com/SummerOfCodeExperience
- your Twitter handle (or another way for publicly contacting you): https://twitter.com/kastauyra
- your email address: laurynas.biveinis@gmail.com

**Comment by jfg956** [comment]
I have seen this, I will look at this in the next days.

**Comment by jfg956** [comment]
Done.
