### ISSUE TITLE
Add github.blog feed in a smart way.

### ISSUE THREAD

**Issue by jfg956** [oursqlcommunity-org/planet#7]
The post (1) arrived to Planet MySQL and not to Planet for the MySQL Community.  But we probably do not want all of github.blog.  This needs either implementing filtering, or lobbying GitHub to provide a MySQL-and-Variants feed.

(1): https://github.blog/2020-05-20-three-bugs-in-the-go-mysql-driver/

**Comment by shlomi-noach** [comment]
suggested filtering:

- if post content contains mysql/percona/mariadb, case insensitive
- if RSS `<category>` field contains mysql/percona/mariadb, case insensitive
  At least for WordPress-based blogs, any tags/categories associated with the post are exported as `<category>` tags.

**Comment by jfg956** [comment]
Thanks Shlomi for the suggestions.  I think it would be easy to add filtering to _ALL_ posts, but I do not want to do this (at least not now).  My favorite solution would be to have a tagged feed for all blogs that have mixed content, but I realize that I cannot impose that to all.  Pythian and Severlnines did it (you are also doing it for your blog), Percona agreed to do it (2), and I would prefer more blogs to do this and we should soon have less MongoDB or Postgres content coming from the Percona blogs on Planet for the MySQL Community.

(2): https://github.com/oursqlcommunity-org/planet/issues/6

Filtering some feed would be my "plan B".  Until I take time to implement that plan B (or that I receive a contribution), we will have to accept irrelevant content on the aggregator AND/OR that some feeds that might provide some good content are not included because they also provide a lot of noise.  In the case of Geeky Hacker that started this discussion in Slack, maybe their feed brings more noise than signal to the aggregator and should be removed until filtering is implemented.  If you want to lead this discussion in MySQL Slack or somewhere else, feel free to do it.  And thanks again for your suggestion.

**Comment by jfg956** [comment]
I implemented filtering via rss.app.  This is costing me a monthly fee, but probably more simple than implementing this myself.

https://github.com/oursqlcommunity-org/planet/commit/51858c874d9dcf4c3564610bdf5c5bf019a0765e

Closing.
