### ISSUE TITLE
Remove fellowshipofdata blog

### ISSUE THREAD

**Issue by vgrippa** [oursqlcommunity-org/planet#98]
Hi Jean-François,

Please remove the fellowshipofdata blog since it was deactivated.

Thanks,

**Comment by jfg956** [comment]
I saw this, I will do this in the next days.  Thanks Fro opening the issue Vinicius and for keeping Planet for the Community clean.

**Comment by jfg956** [comment]
Done in commit below, closing.
https://github.com/oursqlcommunity-org/planet/commit/4e1f9b5bfe08b41f1ad4e339ed406df3f4f0f718
